### ISSUE TITLE
Docker 초반 세팅 설치

### ISSUE THREAD

**Issue by IMRaccoon** [Konkuk-JJabaries/Docker-Study#1]
초기 세팅이랑 기본적으로 알아야될 내용들 적어서

Directory 에 따로 파고 md파일로 만들어주세용 

다른 사람들도 md파일만 보고 따라할 수 있도록 조금 구체적으로 해주시고

배경지식에 필요한 것들도 link 만들어주세요옹

**Comment by EmptyPaper** [comment]
aws , docker 같이 올림

**Comment by s5kywa1k3r** [comment]
다른 사람들이 따라 할 수 있는 요소가 있어야 하는지 궁금합니다.
향후 생각되는 것은 각 개발팀 (Front, Backend, DB)이 어떻게 개발을 할 건지 확인 후 저희가 개발된 코드를 연결하는 작업을 할 예정인데 이 Docker 자체를 만드는 과정 자체가 어렵지는 않지만 과연 md에 필요한 요소인지 의문이 듭니다.

**Comment by IMRaccoon** [comment]
다른 사람이 따라 할 수 있는 요소가 있어야 하는 이유는

1. 다같이 공부하자는 취지에서 진행하는 것
2. 팀내에서도 아는 지식의 범위가 다름
3. 다른 사람에게 따라할 수 있도록 구체적으로 확인하면서 지식의 깊이가 깊어짐
4. 공부한 내용에 대한 흔적을 남기고 다음에 다시 보게 될 수도 있음

말했다시피 당장 급한건 docker나 aws가 아니기 때문에 공부에 치중하면서 해주시면 됩니당
인력낭비라구 생각하지 마시구, 귀찮더라도 작성은 부탁드려용

@Konkuk-JJabaries/new-generation-5erb3r

**Comment by IMRaccoon** [comment]
고생햇어유 작성하느라
