### ISSUE TITLE
Super Docker Express Code 생성

### ISSUE THREAD

**Issue by s5kywa1k3r** [Konkuk-JJabaries/Docker-Study#10]
# Super Docker Express Code 생성

## 구조
\<front> <-> \<super> <-> \<API> or \<DB>

## 분기 순서
1. super docker에서 DB 확인
2. DB에 물품이 존재할 경우
2-1. DB -> super에 response
2-2. jump to 4
3. DB에 물품이 존재하지 않을 경우
3-1. API에 물품 정보 request
3-2. API -> DB에 물품 정보 저장
3-3. DB -> super에 response
4. super -> front로 response

## 기타 내용
- 구조가 바뀌거나 순서에 이상이 있다면 comment 해주세요
- 필요 모듈이 있으면 comment 해주세요

**Comment by IMRaccoon** [comment]
그렇게 할 예정이었습니다. 지금 프론트 팀과 더 토의후에 진행할 예정입니다.

다들 확인 한번씩 하고 제 comment에 이모지 달아주거나

추가로 덧붙일 말 있으면 말해주세요

**Comment by s5kywa1k3r** [comment]
Docker 컨테이너 구조의 의견이 갈리는 부분이 있어서 정정합니다.

컨테이너 방식: \<front> \<-> \<super + api> \<-> \<db>
