### ISSUE TITLE
AWS 초반 세팅 설치

### ISSUE THREAD

**Issue by IMRaccoon** [Konkuk-JJabaries/Docker-Study#2]
Docker랑 마찬가지로 초반 설정법, 설치법

그리고 필요한 배경지식들 해서 Directory따로 만들어서 작업해주세용

**Comment by EmptyPaper** [comment]
[Docker&AWS_Week1.pdf](https://github.com/Konkuk-JJabaries/Docker-Study/files/4005014/Docker.AWS_Week1.pdf)

**Comment by IMRaccoon** [comment]
고생햇습니당 감사유
