### ISSUE TITLE
각 Team 별로 서버 구동에 필요한 라이브러리 정보 요청

### ISSUE THREAD

**Issue by s5kywa1k3r** [Konkuk-JJabaries/Docker-Study#3]
Docker 개발을 위하여 각 팀별 개발 환경 및 라이브러리/API 정보가 필요합니다.

각 팀별로 개발하는 API혹은 FrontEnd에 대하여 사용하는 라이브러리 및 API가
서버에서 구동하기 위하여 아래 두 정보를 요청드립니다. 

1. 각 Team 별 개발/실행 환경 정보
2. 각 Team 별 사용 라이브러리/API 정보

p.s. Server/DB Team 정보는 추후에 요청드리겠습니다. Comment 달지 않으셔도 됩니다.

**Comment by dearyeon** [comment]
npm : 6.13.4
nodejs : 12.14.0
ts : 3.7.4

**Comment by s5kywa1k3r** [comment]
Backend 추가 설치 모듈 ts-node: 8.5.4 확인했습니다.
추가적으로 request, request-promise 모듈이 파악되었는데 이 모듈들에 대한 버전 요청드립니다.

**Comment by IMRaccoon** [comment]
backend 팀 모듈은 제가 확인해보고 안정적인 모듈 찾아서 버전 다시 알려드릴게요
서버팀도 자체적으로 안정적인 모듈 버전 찾아서 알려드리겟습니당

**Comment by IMRaccoon** [comment]
backend 팀 npm이랑 nodejs, ts 버전 다 맞는지 확인부탁드립니다

**Comment by dearyeon** [comment]
다 똑같습니다~!

**Comment by IMRaccoon** [comment]
Front 팀은 JavaScript, HTML, CSS로 build 된 파일로 올라올테고 거기에 대한 실행은 Server 팀에서 맡아 진행할테니 그 점 파악하시고 해결되었다면 close해주세용 node, npm, typescript 버전은 server 팀도 동일합니다
