### ISSUE TITLE
Docker-Study 파일 생성 규칙 제안

### ISSUE THREAD

**Issue by s5kywa1k3r** [Konkuk-JJabaries/Docker-Study#4]
# Docker-Study 파일 생성 규칙 제안
## 제안 개요
-  주별로 공부하는게 아닌 그때 그때 공부한 것을 업로드 하는게 어떻겠나 싶어서 제안
## 방식
-  현재 Docker/Week2 폴더에 Docker 관련 Markdown을 올렸는데 공부한 것을 Markdown에 적용하여 명령어 및 작성 방법을 보존하는게 나을것 같다는 의견

## 적용이 된다면?
- 현재 week 별 폴더를 제거하고 Docker 폴더 하나에 Markdown만 있는 형태로 적용.

**Comment by IMRaccoon** [comment]
나중에 주 별 설명이 가능할까가 조금 걱정스럽습니당 

이게 막 합쳐지면 정신 없을까봐... 뭐 저한테만 얘기하는거니깐 상관은 없는데

원래는 저한테만 얘기하는게 아니라 전체 발표식으로 진행하려고 했었던 거엿는데 저랑만 하는걸로 하게 됫으니

편한 방식을 도입해주세여

**Comment by s5kywa1k3r** [comment]
이 github는 주별로 하기에는 너무 뒤죽박죽인 지식이 너무 많습니다.
당장 dockerfile format만 해도 어떤 주에는 이 명령어에 대해 공부하고 그다음에는 다음 명령어를 공부하게 되고 다시 기억을 되짚어보게 되는 경우가 많은데 주차별로 찾는 것보단 하나의 파일로 각 분야를 관리하는게 좋을거 같아서 제안드렸습니다.

**Comment by IMRaccoon** [comment]
그게 더 나아 보입니당 

다른 팀같은 경우에는 개발을 진행하면서 직관적으로 보이는 부분이 있어서 

주차별로 정리하는 게 훨씬 더 가독성이 좋겠지만

Docker & AWS 같은 경우에는 그게 덜하다는 걸 인지하고 있으니 아예 하나에 병합하고

추가로 계속 덧붙이는 작업으로 진행해주세용

**Comment by IMRaccoon** [comment]
제가 잘못 인지했거나 문제가 있을 경우에는 다시 comment 달아주시구

해결 된거면 close 해주세요옹
